# Generated by Django 4.1.2 on 2022-11-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('D', 'Dollars'), ('R', 'Rubles'), ('E', 'Euro')], default='R', max_length=1),
        ),
    ]
