# Generated by Django 4.1.2 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_actor_movie_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_email',
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=7),
        ),
    ]
