# Generated by Django 4.1.2 on 2022-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_director_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
