# Generated by Django 4.1.2 on 2022-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
